input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {

}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-boot-logs-%{+YYYY.MM.dd}"
    user => "${ES_USER}"
    password => "${ES_PWD}"

    manage_template => false
    ilm_enabled => false

    ssl_verification_mode => "none"
    retry_on_conflict => 5
  }

  # Debug output (optional)
  stdout {
    codec => rubydebug
  }
}