spring.application.name=backend

ALLOW_ORIGINS=http://localhost:5173

jwt.secret.key=${JWT_SECRET_KEY:t2YO0HdF3asOEgMEy9g2YQ9N9Jtwq+op9Ir5VnIYIYs=}

spring.mvc.converters.preferred-json-mapper=jackson3

spring.datasource.url=jdbc:mysql://localhost:3306/database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=your_app_user
spring.datasource.password=your_app_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#mins
jwt.accessToken.expirationTime=15

#days
jwt.refreshToken.expirationTime=7

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.database=${REDIS_DATABASE:0}
spring.data.redis.timeout=${REDIS_TIMEOUT:2000ms}
spring.data.redis.lettuce.pool.max-active=${REDIS_POOL_MAX_ACTIVE:50}
spring.data.redis.lettuce.pool.max-wait=${REDIS_POOL_MAX_WAIT:-1s}
spring.data.redis.lettuce.pool.max-idle=${REDIS_POOL_MAX_IDLE:50}
spring.data.redis.lettuce.pool.min-idle=${REDIS_POOL_MIN_IDLE:0}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_API_KEY}
cloudinary.api-secret=${CLOUD_API_SECRET}

#Stripe
stripe.secret.key=${STRIPE_SECRET}
stripe.webhook.secret=${WEBHOOK_SECRET}
domain.url=http://localhost:8080
