spring.application.name=backend

ALLOW_ORIGINS=${CORRS:http://localhost:5173}

jwt.secret.key=${JWT_SECRET_KEY:t2YO0HdF3asOEgMEy9g2YQ9N9Jtwq+op9Ir5VnIYIYs=}

DEFAULT_PASSWORD=${DEFAULT_USER_PASSWORD:123456}

RATE_LIMIT_PER_IP=${RATE_LIMIT:40}

spring.mvc.converters.preferred-json-mapper=jackson3

#Database connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/auction_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:your_app_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:your_app_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#mins
jwt.accessToken.expirationTime=15

#days
jwt.refreshToken.expirationTime=7

# Redis Configuration
spring.data.redis.url=${REDIS_URL:}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.database=${REDIS_DATABASE:0}
spring.data.redis.timeout=${REDIS_TIMEOUT:2000ms}
spring.data.redis.lettuce.pool.max-active=${REDIS_POOL_MAX_ACTIVE:50}
spring.data.redis.lettuce.pool.max-wait=${REDIS_POOL_MAX_WAIT:-1s}
spring.data.redis.lettuce.pool.max-idle=${REDIS_POOL_MAX_IDLE:50}
spring.data.redis.lettuce.pool.min-idle=${REDIS_POOL_MIN_IDLE:0}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL:false}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_API_KEY}
cloudinary.api-secret=${CLOUD_API_SECRET}

#Stripe
stripe.secret.key=${STRIPE_SECRET}
stripe.webhook.secret=${WEBHOOK_SECRET}
domain.url=${BACKEND_URL:http://localhost:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

#reCAPTCHA
google.recaptcha.secret=${RECAPTCHA_SECRET:6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe}
google.recaptcha.verify.url=https://www.google.com/recaptcha/api/siteverify

# swagger
springdoc.swagger-ui.url=/v3/api-docs

springdoc.swagger-ui.disable-swagger-default-url=false

springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha

#Google login
google.client-id=${GOOGLE_CLIENT_ID}

#RENDER
server.port=${PORT:8080}